### ISSUE TITLE
Ejercicio TIC TAC

### ISSUE THREAD

**Issue by franlu** [Alexnovallas10/ProgramacionPS#3]

**Comment by Alexnovallas10** [comment]
Commit Ejercicio TIC TAC 2acc3000c78fbaf118c31d55abf6ca2fe10f4c7d

Ficheros;
-[Actividad_2_tic](https://github.com/Alexnovallas10/ProgramacionPS/blob/master/src/P02_Hilos/Actividad_2_tic.java)
-[Actividad_2_tac](https://github.com/Alexnovallas10/ProgramacionPS/blob/master/src/P02_Hilos/Actividad_2_tac.java)
-[Actividad_2](https://github.com/Alexnovallas10/ProgramacionPS/blob/master/src/P02_Hilos/Actividad_2.java)

**Comment by franlu** [comment]
Buen trabajo :-)
